name: run-tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        laravel: [ 11.*, 10.*, 9.*, 8.*, 7.*, 6.*, 5.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 11.*
            testbench: 9.*
            php: 8.3

          - laravel: 10.*
            testbench: 8.*
            php: 8.3

          - laravel: 9.*
            testbench: 7.*
            php: 8.2

          - laravel: 8.*
            testbench: 6.*
            php: 8.1

          - laravel: 7.*
            testbench: 5.*
            php: 8.0

          - laravel: 6.*
            testbench: 4.*
            php: 8.0

          - laravel: 5.*
            testbench: 3.*
            php: 7.4

    name: ${{ matrix.os }} - P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
